# These are supported funding model platforms

# GitHub Sponsors
github: [RaffiDevYT]

# Custom Donation Links (Saweria, Trakteer, PayPal)
custom: [
  'https://saweria.co/RaffiDevYT',
  'https://trakteer.id/RaffiDevYT',
  'https://paypal.me/RaffiDevYT'
]
